# -*- coding: utf-8 -*-
"""data_acquisition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bGhknz7hVJMOtox0mHpx2PtQbCpWMsKz
"""

# -*- coding: utf-8 -*-
"""Data acquisition utilities for satellite imagery."""

import os
import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry
from datetime import datetime, timedelta
import pytz
from pystac_client import Client
from shapely.geometry import box

from .config import STAC_API_URL, DEFAULT_CLOUD_COVER_THRESHOLD, DEFAULT_DATE_RANGE_DAYS


class DataDownloader:
    """Handles downloading of remote files with retry logic."""

    def __init__(self, max_retries=3, timeout=60):
        self.session = requests.Session()
        retries = Retry(total=max_retries, connect=None, read=None, redirect=None, status=max_retries)
        self.session.mount('https://', HTTPAdapter(max_retries=retries))
        self.timeout = timeout

    def download_file(self, url, output_path):
        """Download a file from URL to local path."""
        try:
            response = self.session.get(url, timeout=self.timeout)
            response.raise_for_status()
            with open(output_path, 'wb') as file:
                file.write(response.content)
            return True
        except requests.exceptions.RequestException as e:
            raise Exception(f"Failed to download {url}: {e}")


class SatelliteDataAcquisition:
    """Handles satellite data search and acquisition via STAC API."""

    def __init__(self, stac_url=STAC_API_URL):
        self.client = Client.open(stac_url)
        self.downloader = DataDownloader()

    def search_sentinel2_data(self, region_of_interest, target_date_str,
                            cloud_cover_threshold=DEFAULT_CLOUD_COVER_THRESHOLD,
                            date_range_days=DEFAULT_DATE_RANGE_DAYS):
        """Search for Sentinel-2 data matching criteria."""
        target_date = datetime.strptime(target_date_str, '%Y-%m-%d').replace(tzinfo=pytz.UTC)
        start_date = target_date - timedelta(days=date_range_days)
        end_date = target_date + timedelta(days=date_range_days)
        date_range = f"{start_date.strftime('%Y-%m-%d')}/{end_date.strftime('%Y-%m-%d')}"

        search = self.client.search(
            collections=["sentinel-2-l2a"],
            intersects=region_of_interest.__geo_interface__,
            datetime=date_range,
            query={"eo:cloud_cover": {"lt": cloud_cover_threshold}}
        )

        items = list(search.items())
        if not items:
            raise Exception(f"No Sentinel-2 products found with <{cloud_cover_threshold}% cloud cover")

        # Find closest item to target date
        selected_item = min(items, key=lambda x: abs(x.datetime - target_date))
        return selected_item

    def download_benchmark_data(self, url, output_filename):
        """Download benchmark hyperspectral data."""
        return self.downloader.download_file(url, output_filename)