# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bGhknz7hVJMOtox0mHpx2PtQbCpWMsKz
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Main execution script for hyper-ez hyperspectral enhancement."""

import os
from hyper_ez.config import (
    setup_matplotlib_style, BENCHMARK_DATA_URL,
    DEFAULT_PATCH_SIZE, DEFAULT_STRIDE, DEFAULT_GUIDE_RADIUS, DEFAULT_DETAIL_WEIGHT
)
from hyper_ez.data_acquisition import SatelliteDataAcquisition
from hyper_ez.geospatial_utils import GeospatialProcessor
from hyper_ez.image_processing import HyperspectralProcessor
from hyper_ez.visualization import HyperspectralVisualizer


def main():
    """Main execution function."""
    # Setup
    setup_matplotlib_style()

    # Initialize processors
    data_acquisition = SatelliteDataAcquisition()
    geospatial_processor = GeospatialProcessor()
    hyperspectral_processor = HyperspectralProcessor()
    visualizer = HyperspectralVisualizer()

    # Configuration
    benchmark_filename = 'benchmark_hyperspectral.tif'
    sentinel_filename = 'processed_sentinel2.tif'
    esri_filename = 'high_resolution_imagery.tif'
    target_date = '2024-07-20'

    try:
        # Step 1: Download benchmark hyperspectral data
        print("Downloading benchmark hyperspectral data...")
        data_acquisition.download_benchmark_data(BENCHMARK_DATA_URL, benchmark_filename)

        # Step 2: Extract spatial metadata from benchmark data
        print("Extracting spatial metadata...")
        region_of_interest, reference_bounds, reference_crs, reference_resolution = \
            geospatial_processor.extract_spatial_metadata(benchmark_filename)

        print(f"Reference CRS: {reference_crs}, Resolution: {reference_resolution}, Bounds: {reference_bounds}")

        # Step 3: Search and acquire Sentinel-2 data
        print("Searching for Sentinel-2 data...")
        selected_sentinel_item = data_acquisition.search_sentinel2_data(region_of_interest, target_date)
        print(f"Selected Sentinel-2 item: {selected_sentinel_item.id} "
              f"(Date: {selected_sentinel_item.datetime.date()}, "
              f"Cloud cover: {selected_sentinel_item.properties['eo:cloud_cover']}%)")

        # Step 4: Process Sentinel-2 bands
        print("Processing Sentinel-2 bands...")
        processed_band_paths = geospatial_processor.process_sentinel2_bands(
            selected_sentinel_item, reference_bounds, reference_crs
        )

        # Step 5: Stack bands into multi-band GeoTIFF
        print("Creating multi-band Sentinel-2 GeoTIFF...")
        geospatial_processor.stack_bands_to_multiband(processed_band_paths, sentinel_filename)

        # Step 6: Acquire high-resolution imagery
        print("Acquiring high-resolution imagery...")
        esri_path = hyperspectral_processor.acquire_high_resolution_imagery(
            reference_bounds, reference_crs
        )

        # Step 7: Perform initial enhancement with Sentinel-2
        print("Performing initial hyperspectral enhancement...")
        enhanced_hyperspectral = hyperspectral_processor.enhance_hyperspectral_image(
            sentinel_filename, benchmark_filename,
            patch_size=DEFAULT_PATCH_SIZE, stride=DEFAULT_STRIDE,
            guide_radius=DEFAULT_GUIDE_RADIUS, detail_weight=DEFAULT_DETAIL_WEIGHT
        )

        print(f"Enhanced hyperspectral shape: {enhanced_hyperspectral.shape}")

        # Step 8: Save intermediate enhanced data
        temp_enhanced_path = 'temp_enhanced_hyperspectral.tif'
        hyperspectral_processor.save_enhanced_data(
            enhanced_hyperspectral, sentinel_filename, temp_enhanced_path
        )

        # Step 9: Perform super-enhancement with high-resolution imagery
        print("Performing super-enhancement...")
        super_enhanced_hyperspectral = hyperspectral_processor.enhance_hyperspectral_image(
            esri_path, temp_enhanced_path,
            patch_size=DEFAULT_PATCH_SIZE, stride=DEFAULT_STRIDE,
            guide_radius=DEFAULT_GUIDE_RADIUS, detail_weight=DEFAULT_DETAIL_WEIGHT
        )

        print(f"Super-enhanced hyperspectral shape: {super_enhanced_hyperspectral.shape}")

        # Step 10: Visualize results
        print("Visualizing results...")
        visualizer.display_false_color_composite(
            super_enhanced_hyperspectral, "Super-Enhanced Hyperspectral False Color Composite"
        )

        visualizer.display_false_color_composite(
            enhanced_hyperspectral, "Enhanced Hyperspectral False Color Composite"
        )

        # Cleanup temporary files
        if os.path.exists(temp_enhanced_path):
            os.remove(temp_enhanced_path)

        print("Processing completed successfully!")

    except Exception as e:
        print(f"Error during processing: {e}")
        # Cleanup on error
        temp_files = [temp_enhanced_path] if 'temp_enhanced_path' in locals() else []
        for temp_file in temp_files:
            if os.path.exists(temp_file):
                os.remove(temp_file)
        raise


if __name__ == "__main__":
    main()