# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bGhknz7hVJMOtox0mHpx2PtQbCpWMsKz
"""

# -*- coding: utf-8 -*-
"""Configuration settings for hyper-ez package."""

import matplotlib as mpl
import matplotlib.pyplot as plt

# STAC API Configuration
STAC_API_URL = "https://earth-search.aws.element84.com/v1"
ESRI_IMAGERY_URL = "https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/export"
BENCHMARK_DATA_URL = "https://raw.githubusercontent.com/naikp13/hsi_enhancement/main/data/enmap_valclip_marinkas.tif"

# Processing Parameters
DEFAULT_CLOUD_COVER_THRESHOLD = 10
DEFAULT_DATE_RANGE_DAYS = 100
TARGET_RESOLUTION_METERS = 10.0
HIGH_RESOLUTION_METERS = 2.0

# Enhancement Parameters
DEFAULT_PATCH_SIZE = 12
DEFAULT_STRIDE = 1
DEFAULT_GUIDE_RADIUS = 10
DEFAULT_DETAIL_WEIGHT = 1

# Sentinel-2 Band Mapping
SENTINEL2_BAND_MAPPING = {
    'B01': 'coastal',
    'B02': 'blue',
    'B03': 'green',
    'B04': 'red',
    'B05': 'rededge1',
    'B06': 'rededge2',
    'B07': 'rededge3',
    'B08': 'nir',
    'B8A': 'nir08',
    'B09': 'nir09',
    'B11': 'swir16',
    'B12': 'swir22'
}

SENTINEL2_BANDS = list(SENTINEL2_BAND_MAPPING.keys())

# Visualization bands for RGB display
DEFAULT_RGB_BANDS = [65, 45, 35]

def setup_matplotlib_style():
    """Configure matplotlib plotting style."""
    plt.style.use(['default'])
    mpl.rcParams['font.size'] = 18
    mpl.rcParams['figure.titleweight'] = 'normal'
    mpl.rcParams['savefig.dpi'] = 350
    mpl.rcParams['axes.spines.bottom'] = True
    mpl.rcParams['axes.spines.left'] = True
    mpl.rcParams['axes.spines.right'] = True
    mpl.rcParams['axes.spines.top'] = True
    plt.rcParams["axes.edgecolor"] = "black"
    plt.rcParams["axes.linewidth"] = 2
