# -*- coding: utf-8 -*-
"""geospatial_utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bGhknz7hVJMOtox0mHpx2PtQbCpWMsKz
"""

# -*- coding: utf-8 -*-
"""Geospatial processing utilities."""

import os
import numpy as np
import rasterio
from rasterio.crs import CRS
from rasterio.warp import transform_bounds, reproject, Resampling
from rasterio.windows import from_bounds
from rasterio.transform import from_bounds as transform_from_bounds
from shapely.geometry import box
import gc

from .config import SENTINEL2_BAND_MAPPING, TARGET_RESOLUTION_METERS
from .data_acquisition import DataDownloader


class GeospatialProcessor:
    """Handles geospatial data processing operations."""

    def __init__(self):
        self.downloader = DataDownloader()

    def extract_spatial_metadata(self, raster_path):
        """Extract bounding box, CRS, and resolution from raster file."""
        with rasterio.open(raster_path) as dataset:
            bounds = dataset.bounds
            source_crs = dataset.crs
            resolution = dataset.res
            height, width = dataset.height, dataset.width

            if height == 0 or width == 0:
                raise ValueError(f"Invalid dimensions for {raster_path}: height={height}, width={width}")

            # Transform bounds to WGS84 for STAC queries
            if source_crs != CRS.from_epsg(4326):
                bounds_wgs84 = transform_bounds(source_crs, CRS.from_epsg(4326), *bounds)
            else:
                bounds_wgs84 = bounds

            region_of_interest = box(bounds_wgs84[0], bounds_wgs84[1], bounds_wgs84[2], bounds_wgs84[3])
            return region_of_interest, bounds, source_crs, resolution

    def process_sentinel2_bands(self, satellite_item, reference_bounds, reference_crs,
                              target_resolution=TARGET_RESOLUTION_METERS):
        """Download, clip, and resample Sentinel-2 bands."""
        processed_band_paths = []

        for band_name in SENTINEL2_BAND_MAPPING.keys():
            asset_key = SENTINEL2_BAND_MAPPING[band_name]
            band_url = satellite_item.assets[asset_key].href

            temp_path = f"temp_{band_name}.tif"
            output_path = f"resampled_{band_name}.tif"

            try:
                # Download band
                self.downloader.download_file(band_url, temp_path)

                # Process band
                self._clip_and_resample_band(temp_path, output_path, reference_bounds,
                                           reference_crs, target_resolution)

                processed_band_paths.append(output_path)
                os.remove(temp_path)
                gc.collect()

            except Exception as e:
                if os.path.exists(temp_path):
                    os.remove(temp_path)
                raise Exception(f"Error processing band {band_name}: {e}")

        return processed_band_paths

    def _clip_and_resample_band(self, input_path, output_path, reference_bounds,
                               reference_crs, target_resolution):
        """Clip and resample a single band to target resolution."""
        # Validate target_resolution to prevent division by zero
        if target_resolution <= 0:
            print(f"Warning: Invalid target_resolution ({target_resolution}). Using default 10m resolution.")
            target_resolution = 10.0  # Default to 10 meter resolution
            
        with rasterio.open(input_path) as source:
            # Transform reference bounds to source CRS if needed
            if reference_crs != source.crs:
                from rasterio.warp import transform_bounds
                transformed_bounds = transform_bounds(reference_crs, source.crs, 
                                                    reference_bounds.left, reference_bounds.bottom,
                                                    reference_bounds.right, reference_bounds.top)
                clip_bounds = transformed_bounds
            else:
                clip_bounds = (reference_bounds.left, reference_bounds.bottom, 
                             reference_bounds.right, reference_bounds.top)
            
            # Get intersection with source bounds to ensure valid window
            src_bounds = source.bounds
            intersect_left = max(clip_bounds[0], src_bounds.left)
            intersect_bottom = max(clip_bounds[1], src_bounds.bottom)
            intersect_right = min(clip_bounds[2], src_bounds.right)
            intersect_top = min(clip_bounds[3], src_bounds.top)
            
            # Check if there's a valid intersection
            if intersect_left >= intersect_right or intersect_bottom >= intersect_top:
                raise ValueError(f"No intersection between reference bounds and source image bounds")
            
            # Create window from intersected bounds
            try:
                window = from_bounds(intersect_left, intersect_bottom, 
                                   intersect_right, intersect_top, 
                                   transform=source.transform)
                
                # Ensure window has valid dimensions
                if window.width <= 0 or window.height <= 0:
                    raise ValueError(f"Invalid window dimensions: {window.width}x{window.height}")
                    
                band_data = source.read(1, window=window)
                
                # Validate band_data dimensions
                if band_data.size == 0 or band_data.shape[0] == 0 or band_data.shape[1] == 0:
                    raise ValueError(f"Empty band data after windowed read: shape={band_data.shape}")
                    
            except Exception as e:
                print(f"Error creating window or reading data: {e}")
                # Fallback: read entire source and let reproject handle the clipping
                band_data = source.read(1)
                window = None
                intersect_bounds = src_bounds
                
            if window is not None:
                source_transform = source.window_transform(window)
                work_bounds = (intersect_left, intersect_bottom, intersect_right, intersect_top)
            else:
                source_transform = source.transform
                work_bounds = src_bounds
            
            source_crs = source.crs

            # Calculate target dimensions based on the working bounds
            if reference_crs.is_geographic:
                # For geographic coordinates, use source pixel dimensions as reference
                src_res_x, src_res_y = source.res
                
                # Rough conversion for geographic coordinates
                if source.crs.is_geographic:
                    # Convert degrees to approximate meters (rough estimate)
                    src_res_x_meters = abs(src_res_x) * 111000  # 1 degree ≈ 111km
                    src_res_y_meters = abs(src_res_y) * 111000
                else:
                    src_res_x_meters = abs(src_res_x)
                    src_res_y_meters = abs(src_res_y)
                
                # Calculate scale factor
                scale_x = src_res_x_meters / target_resolution
                scale_y = src_res_y_meters / target_resolution
                
                # Apply to actual data dimensions
                target_width = max(1, int(band_data.shape[1] * scale_x))
                target_height = max(1, int(band_data.shape[0] * scale_y))
            else:
                # For projected coordinates
                bounds_width = work_bounds[2] - work_bounds[0]
                bounds_height = work_bounds[3] - work_bounds[1]
                target_width = max(1, int(bounds_width / target_resolution))
                target_height = max(1, int(bounds_height / target_resolution))

            print(f"Debug: Final target dimensions: width={target_width}, height={target_height}")
            print(f"Debug: Band data shape: {band_data.shape}")

            # Create destination transform for the reference bounds (not working bounds)
            destination_transform = rasterio.transform.from_bounds(
                reference_bounds.left, reference_bounds.bottom,
                reference_bounds.right, reference_bounds.top,
                target_width, target_height
            )

            # Create output array with validated dimensions
            resampled_data = np.zeros((target_height, target_width), dtype='uint16')
            
            # Perform reprojection
            reproject(
                source=band_data,
                destination=resampled_data,
                src_transform=source_transform,
                src_crs=source_crs,
                dst_transform=destination_transform,
                dst_crs=reference_crs,
                resampling=Resampling.bilinear
            )

            # Save resampled band
            output_metadata = source.meta.copy()
            output_metadata.update({
                'height': target_height,
                'width': target_width,
                'transform': destination_transform,
                'crs': reference_crs,
                'dtype': 'uint16'
            })

            with rasterio.open(output_path, 'w', **output_metadata) as destination:
                destination.write(resampled_data, 1)

    def stack_bands_to_multiband(self, band_paths, output_path):
        """Stack individual bands into a multi-band GeoTIFF."""
        with rasterio.open(band_paths[0]) as reference:
            metadata = reference.meta.copy()
            metadata.update(count=len(band_paths))

        with rasterio.open(output_path, 'w', **metadata) as destination:
            for band_index, band_path in enumerate(band_paths, 1):
                with rasterio.open(band_path) as source:
                    destination.write(source.read(1), band_index)
                os.remove(band_path)
                gc.collect()