# -*- coding: utf-8 -*-
"""image_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bGhknz7hVJMOtox0mHpx2PtQbCpWMsKz
"""

# -*- coding: utf-8 -*-
"""Image processing and enhancement utilities."""

import os
import numpy as np
import rasterio
from rasterio.crs import CRS
from rasterio.warp import transform_bounds, reproject, Resampling
from rasterio.transform import from_bounds as transform_from_bounds
from hsi_enhancement.src import HSIEnhancer

from .config import (ESRI_IMAGERY_URL, HIGH_RESOLUTION_METERS,
                    DEFAULT_PATCH_SIZE, DEFAULT_STRIDE,
                    DEFAULT_GUIDE_RADIUS, DEFAULT_DETAIL_WEIGHT)
from .data_acquisition import DataDownloader


class HyperspectralProcessor:
    """Handles hyperspectral image enhancement processing."""

    def __init__(self):
        self.downloader = DataDownloader()

    def acquire_high_resolution_imagery(self, reference_bounds, reference_crs,
                                      target_resolution=HIGH_RESOLUTION_METERS):
        """Download and process ESRI World Imagery for super-resolution enhancement."""
        esri_crs = CRS.from_epsg(3857)
        esri_bounds = transform_bounds(reference_crs, esri_crs, *reference_bounds)

        # Calculate target dimensions
        target_width = int((reference_bounds.right - reference_bounds.left) / target_resolution)
        target_height = int((reference_bounds.top - reference_bounds.bottom) / target_resolution)
        
        # Ensure minimum dimensions
        target_width = max(1, target_width)
        target_height = max(1, target_height)
        
        # Limit maximum dimensions to prevent API errors
        max_dimension = 4096
        if target_width > max_dimension or target_height > max_dimension:
            scale_factor = min(max_dimension / target_width, max_dimension / target_height)
            target_width = int(target_width * scale_factor)
            target_height = int(target_height * scale_factor)

        # Prepare ESRI API parameters
        bbox_string = f"{esri_bounds[0]},{esri_bounds[1]},{esri_bounds[2]},{esri_bounds[3]}"
        request_params = {
            'bbox': bbox_string,
            'bboxSR': esri_crs.to_epsg(),
            'size': f"{target_width},{target_height}",
            'format': 'tiff',
            'pixelType': 'U8',
            'noData': '0',
            'f': 'image'
        }

        temp_esri_path = 'temp_esri_imagery.tif'
        output_path = 'high_resolution_imagery.tif'

        try:
            # Download ESRI imagery
            response = self.downloader.session.get(ESRI_IMAGERY_URL, params=request_params,
                                                 timeout=self.downloader.timeout)
            response.raise_for_status()
            
            # Validate response content
            content_type = response.headers.get('content-type', '').lower()
            if 'image' not in content_type and 'tiff' not in content_type:
                # Check if response contains error message
                try:
                    response_text = response.content.decode('utf-8')[:500]  # First 500 chars
                    if 'error' in response_text.lower() or 'html' in response_text.lower():
                        raise Exception(f"API returned error response: {response_text}")
                except UnicodeDecodeError:
                    pass  # Binary content, might be valid image
            
            # Check content length
            if len(response.content) < 100:  # Very small response likely an error
                try:
                    error_msg = response.content.decode('utf-8')
                    raise Exception(f"API returned small response (likely error): {error_msg}")
                except UnicodeDecodeError:
                    raise Exception(f"API returned unexpectedly small response: {len(response.content)} bytes")
            
            # Check if content starts with TIFF magic bytes
            tiff_signatures = [b'II*\x00', b'MM\x00*']  # Little-endian and big-endian TIFF
            if not any(response.content.startswith(sig) for sig in tiff_signatures):
                # Try to decode first part to see what we got
                try:
                    preview = response.content[:200].decode('utf-8', errors='ignore')
                    raise Exception(f"Response is not a valid TIFF file. Content preview: {preview}")
                except:
                    raise Exception(f"Response is not a valid TIFF file. Content length: {len(response.content)} bytes")

            with open(temp_esri_path, 'wb') as file:
                file.write(response.content)
            
            # Verify the downloaded file can be opened
            try:
                with rasterio.open(temp_esri_path) as test_src:
                    if test_src.width == 0 or test_src.height == 0:
                        raise Exception("Downloaded image has zero dimensions")
            except Exception as e:
                raise Exception(f"Downloaded file is not a valid raster: {e}")

            # Reproject to reference CRS
            self._reproject_esri_imagery(temp_esri_path, output_path, reference_bounds,
                                       reference_crs, esri_bounds, target_width, target_height)

            os.remove(temp_esri_path)
            return output_path

        except Exception as e:
            if os.path.exists(temp_esri_path):
                os.remove(temp_esri_path)
            raise Exception(f"Error acquiring high-resolution imagery: {e}")

    def _reproject_esri_imagery(self, input_path, output_path, reference_bounds,
                               reference_crs, esri_bounds, target_width, target_height):
        """Reproject ESRI imagery to reference coordinate system."""
        with rasterio.open(input_path) as source:
            source_data = source.read()
            source_crs = CRS.from_epsg(3857)

            source_transform = transform_from_bounds(
                esri_bounds[0], esri_bounds[1], esri_bounds[2], esri_bounds[3],
                source.width, source.height
            )

            destination_transform = transform_from_bounds(
                reference_bounds.left, reference_bounds.bottom,
                reference_bounds.right, reference_bounds.top,
                target_width, target_height
            )

            reprojected_data = np.zeros((source_data.shape[0], target_height, target_width), dtype='uint8')

            reproject(
                source=source_data,
                destination=reprojected_data,
                src_transform=source_transform,
                src_crs=source_crs,
                dst_transform=destination_transform,
                dst_crs=reference_crs,
                resampling=Resampling.bilinear
            )

            output_metadata = source.meta.copy()
            output_metadata.update({
                'height': target_height,
                'width': target_width,
                'transform': destination_transform,
                'crs': reference_crs,
                'dtype': 'uint8',
                'count': source_data.shape[0]
            })

            with rasterio.open(output_path, 'w', **output_metadata) as destination:
                destination.write(reprojected_data)

    def enhance_hyperspectral_image(self, multispectral_path, hyperspectral_path,
                                  patch_size=DEFAULT_PATCH_SIZE, stride=DEFAULT_STRIDE,
                                  guide_radius=DEFAULT_GUIDE_RADIUS, detail_weight=DEFAULT_DETAIL_WEIGHT):
        """Perform hyperspectral image enhancement using HSIEnhancer."""
        try:
            enhancer = HSIEnhancer(multispectral_path, hyperspectral_path)
            enhanced_data = enhancer.fuse_to_enhance(
                patch_size=patch_size,
                stride=stride,
                guide_radius=guide_radius,
                detail_weight=detail_weight
            )
            return enhanced_data
        except Exception as e:
            raise Exception(f"Error in hyperspectral enhancement: {e}")

    def save_enhanced_data(self, enhanced_data, reference_path, output_path):
        """Save enhanced hyperspectral data to GeoTIFF."""
        with rasterio.open(reference_path) as reference:
            metadata = reference.meta.copy()
            metadata.update(count=enhanced_data.shape[2], dtype='float32')

        with rasterio.open(output_path, 'w', **metadata) as destination:
            for band_index in range(enhanced_data.shape[2]):
                destination.write(enhanced_data[:, :, band_index], band_index + 1)