# -*- coding: utf-8 -*-
"""visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bGhknz7hVJMOtox0mHpx2PtQbCpWMsKz
"""

# -*- coding: utf-8 -*-
"""Visualization utilities for hyperspectral data."""

import numpy as np
import matplotlib.pyplot as plt
from .config import DEFAULT_RGB_BANDS


class HyperspectralVisualizer:
    """Handles visualization of hyperspectral imagery."""

    def __init__(self, rgb_bands=None):
        self.rgb_bands = rgb_bands or DEFAULT_RGB_BANDS

    def display_false_color_composite(self, hyperspectral_data, title="Hyperspectral False Color Composite",
                                    figure_size=(10, 8), rgb_bands=None):
        """Display false color composite of hyperspectral data."""
        display_bands = rgb_bands or self.rgb_bands

        # Ensure selected bands exist in the data
        available_bands = [band for band in display_bands if band < hyperspectral_data.shape[2]]

        if len(available_bands) < 3:
            # Fallback to first three bands if specified bands don't exist
            available_bands = [0, 1, 2] if hyperspectral_data.shape[2] >= 3 else list(range(hyperspectral_data.shape[2]))

        # Extract RGB data and normalize
        rgb_data = hyperspectral_data[..., available_bands[:3]]
        normalized_data = np.clip(rgb_data / np.nanmax(rgb_data), 0, 1)

        plt.figure(figsize=figure_size)
        plt.imshow(normalized_data)
        plt.title(title, fontweight='bold')
        plt.axis("on")
        plt.show()

    def compare_enhancements(self, original_data, enhanced_data, super_enhanced_data=None):
        """Compare original and enhanced hyperspectral data."""
        fig, axes = plt.subplots(1, 3 if super_enhanced_data is not None else 2, figsize=(15, 5))

        # Original data
        self._plot_on_axis(axes[0], original_data, "Original HSI")

        # Enhanced data
        self._plot_on_axis(axes[1], enhanced_data, "Enhanced HSI")

        # Super-enhanced data (if provided)
        if super_enhanced_data is not None:
            self._plot_on_axis(axes[2], super_enhanced_data, "Super-Enhanced HSI")

        plt.tight_layout()
        plt.show()

    def _plot_on_axis(self, axis, hyperspectral_data, title):
        """Plot hyperspectral data on a specific axis."""
        available_bands = [band for band in self.rgb_bands if band < hyperspectral_data.shape[2]]

        if len(available_bands) < 3:
            available_bands = [0, 1, 2] if hyperspectral_data.shape[2] >= 3 else list(range(hyperspectral_data.shape[2]))

        rgb_data = hyperspectral_data[..., available_bands[:3]]
        normalized_data = np.clip(rgb_data / np.nanmax(rgb_data), 0, 1)

        axis.imshow(normalized_data)
        axis.set_title(title, fontweight='bold')
        axis.axis("on")